version: "3.1"
services:
  app:
    build: .
    container_name: VideoStreamingApp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
